name: CheckMake

on: [push, pull_request]

env:
  GOPATH: /root/go

jobs:
  checkmake:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y golang make pandoc git
    - name: Build checkmake
      env:
        BUILDER_NAME: "Paulo Matos"
      run: |
        go get github.com/mrtazz/checkmake
        cd $GOPATH/src/github.com/mrtazz/checkmake
        make
    - name: Check
      run: $GOPATH/src/github.com/mrtazz/checkmake/checkmake Makefile
