name: Coverity CI

on:
  push:
    branches:
      - master

jobs:
  covbuild:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update 
        apt-get install -y make curl gcc wget git
    - name: Install Coverity Build
      run: |
        wget https://scan.coverity.com/download/linux64 --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=pmatos%2Frattle" -O coverity_tool.tgz
        tar -xvf coverity_tool.tgz
    - name: Build
      run: cov-analysis-linux64-2019.03/bin/cov-build --dir cov-int make
    - name: Submit results
      run: |
        export COMMITID="git_sha$(git rev-parse --short HEAD)"
        tar czf rattle.tgz cov-int
        curl --form token=${{ secrets.COVERITY_TOKEN }} --form email=pmatos@linki.tools --form file=@rattle.tgz --form version=$COMMITID --form description="Experimental R7RS Scheme Compiler" https://scan.coverity.com/builds\?project\=pmatos%2Frattle
