name: CppCheck

on: [push, pull_request]

jobs:
  cppcheck:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y gcc gcc-8 cppcheck
    - name: Check
      run: cppcheck --enable=all --suppress=missingIncludeSystem -I. -Isrc/ -q src/rattle.c &> cppcheck.log || true
    - name: Check for failure
      run: |
        cat cppcheck.log
        test ! -s "cppcheck.log"
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cppcheck-${{ github.sha }}
        path: cppcheck.log

  
        

  
