name: CppCheck

on: [push, pull_request]

jobs:
  cppcheck:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y gcc gcc-8 cppcheck
    - name: Check
      run: |
        [ -z "$(cppcheck --enable=all --suppress=missingIncludeSystem -I. -Isrc/ -q src/rattle.c 2>&1 )" ]
  
        

  
