name: Fossa

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install fossa-cli
      run: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
    - name: Run fossa
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
      run: fossa test
