name: Linux CI

on: [push, pull_request]

jobs:
  buildtest-glibc:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update 
        apt-get install -y cmake ninja-build gcc gcc-8 g++ g++-8 sudo curl
    - name: Configure
      run: cmake -GNinja -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_BUILD_TYPE=Coverage .
    - name: Build
      run: ninja
    - uses: Bogdanp/setup-racket@v0.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.5'
    - name: Test fixnums
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/fixnum.tests
    - name: Test booleans
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/boolean.tests
    - name: Test characters
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/char.tests
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: integration
        fail_ci_if_error: true
        yml: ./.codecov.yml
          

  buildtest-musl:

    runs-on: ubuntu-latest
    container:
      image: pmatos/alpine-racket:latest
      options: --rm

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apk update
        apk add cmake ninja gcc g++ sudo curl
    - name: Create build dir
      run: mkdir build
    - name: Configure
      working-directory: ./build
      run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - name: Build
      working-directory: ./build
      run: ninja
    - name: Test fixnums
      working-directory: ./build
      run: racket ../tests/script/test.rkt -c "./rattle -e --" ../tests/fixnum.tests
    - name: Test booleans
      working-directory: ./build
      run: racket ../tests/script/test.rkt -c "./rattle -e --" ../tests/boolean.tests
    - name: Test characters
      working-directory: ./build
      run: racket ../tests/script/test.rkt -c "./rattle -e --" ../tests/char.tests


  buildtest-vg:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update 
        apt-get install -y cmake ninja-build gcc gcc-8 g++ g++-8 sudo curl valgrind
    - name: Create build dir
      run: mkdir build
    - name: Configure
      working-directory: ./build
      run: cmake -GNinja -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_BUILD_TYPE=Debug ..
    - name: Build
      working-directory: ./build
      run: ninja
    - uses: Bogdanp/setup-racket@v0.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.5'
    - name: Test fixnums
      working-directory: ./build
      run: racket ../tests/script/test.rkt -c "valgrind -q ./rattle -e --" ../tests/fixnum.tests
    - name: Test booleans
      working-directory: ./build
      run: racket ../tests/script/test.rkt -c "valgrind -q ./rattle -e --" ../tests/boolean.tests
    - name: Test characters
      working-directory: ./build
      run: racket ../tests/script/test.rkt -c "valgrind -q ./rattle -e --" ../tests/char.tests
      
