name: Linux CI

on: [push, pull_request]

jobs:
  buildtest-glibc:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update 
        apt-get install -y make gcc gcc-8 g++ g++-8 sudo curl
    - name: Build
      env:
        COVERAGE: 1
      run: make 
    - uses: Bogdanp/setup-racket@v0.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.5'
    - name: Test fixnums
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/fixnum.tests
    - name: Test booleans
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/boolean.tests
    - name: Test characters
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/char.tests
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
          

  buildtest-musl:

    runs-on: ubuntu-latest
    container:
      image: pmatos/alpine-racket:latest
      options: --rm

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apk update
        apk add make gcc g++ sudo curl
    - name: Build
      run: make
    - name: Test fixnums
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/fixnum.tests
    - name: Test booleans
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/boolean.tests
    - name: Test characters
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/char.tests


  buildtest-vg:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update 
        apt-get install -y make gcc gcc-8 g++ g++-8 sudo curl valgrind
    - name: Build
      run: make
    - uses: Bogdanp/setup-racket@v0.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.5'
    - name: Test fixnums
      run: racket tests/script/test.rkt -c "valgrind -q ./rattle -e --" tests/fixnum.tests
    - name: Test booleans
      run: racket tests/script/test.rkt -c "valgrind -q ./rattle -e --" tests/boolean.tests
    - name: Test characters
      run: racket tests/script/test.rkt -c "valgrind -q ./rattle -e --" tests/char.tests
      
