name: Release CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update 
        apt-get install -y cmake ninja-build gcc gcc-8 g++ g++-8
    - name: Create build dir
      run: mkdir build
    - name: Configure
      working-directory: ./build
      run: cmake -GNinja -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ..
    - name: Build
      run: ninja
