name: MacOS CI

on: [push]

jobs:
  buildtest-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check system width
      run: |
        gcc -o sizes scripts/sizes.c
        ./sizes
    - name: Build
      run: make
    - uses: Bogdanp/setup-racket@v0.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.6'
    - name: Run Tests
      run: make tests
