name: MacOS CI

on: [push]

jobs:
  buildtest-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make
    - uses: Bogdanp/setup-racket@v0.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.5'
    - name: Test fixnums
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/fixnum.tests
    - name: Test booleans
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/boolean.tests
    - name: Test characters
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/char.tests
