name: MacOS CI

on: [push]

jobs:
  buildtest-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check system width
      run: |
        gcc -o sizes scripts/sizes.c
        ./sizes
    - name: Build
      run: make
    - uses: Bogdanp/setup-racket@v0.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.5'
    - name: Test null
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/null.tests
    - name: Test fixnums
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/fixnum.tests
    - name: Test booleans
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/boolean.tests
    - name: Test characters
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/char.tests
    - name: Test primitives
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/primitives.tests
    - name: Test if
      run: racket tests/script/test.rkt -c "./rattle -e --" tests/if.tests
